# Generated by Django 3.0 on 2022-02-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('full_name',), 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Возраст студента')),
                ('gpa', models.FloatField(verbose_name='Средний балл')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Group')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ('account',),
            },
        ),
    ]
